// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Scratch database used by `prisma migrate diff/dev` to compute a diff.
    // Never holds application data.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
